/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as IssuesSlugRouteImport } from './routes/issues.$slug'
import { Route as ConfirmTokenRouteImport } from './routes/confirm.$token'
import { Route as AdminSubscribersRouteImport } from './routes/admin_.subscribers'
import { Route as AdminSendRouteImport } from './routes/admin_.send'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminIssuesRouteImport } from './routes/admin_.issues'
import { Route as AdminIssuesIdRouteImport } from './routes/admin_.issues_.$id'

const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSlugRoute = IssuesSlugRouteImport.update({
  id: '/issues/$slug',
  path: '/issues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTokenRoute = ConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin_/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSendRoute = AdminSendRouteImport.update({
  id: '/admin_/send',
  path: '/admin/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesRoute = AdminIssuesRouteImport.update({
  id: '/admin_/issues',
  path: '/admin/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesIdRoute = AdminIssuesIdRouteImport.update({
  id: '/admin_/issues_/$id',
  path: '/admin/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/send': typeof AdminSendRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/send': typeof AdminSendRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/admin_/issues': typeof AdminIssuesRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/send': typeof AdminSendRoute
  '/admin_/subscribers': typeof AdminSubscribersRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/admin_/issues_/$id': typeof AdminIssuesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/admin/issues'
    | '/admin/login'
    | '/admin/send'
    | '/admin/subscribers'
    | '/confirm/$token'
    | '/issues/$slug'
    | '/unsubscribe/$token'
    | '/admin/issues/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/admin/issues'
    | '/admin/login'
    | '/admin/send'
    | '/admin/subscribers'
    | '/confirm/$token'
    | '/issues/$slug'
    | '/unsubscribe/$token'
    | '/admin/issues/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/admin_/issues'
    | '/admin_/login'
    | '/admin_/send'
    | '/admin_/subscribers'
    | '/confirm/$token'
    | '/issues/$slug'
    | '/unsubscribe/$token'
    | '/admin_/issues_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  AdminIssuesRoute: typeof AdminIssuesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSendRoute: typeof AdminSendRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  ConfirmTokenRoute: typeof ConfirmTokenRoute
  IssuesSlugRoute: typeof IssuesSlugRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  AdminIssuesIdRoute: typeof AdminIssuesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$slug': {
      id: '/issues/$slug'
      path: '/issues/$slug'
      fullPath: '/issues/$slug'
      preLoaderRoute: typeof IssuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$token': {
      id: '/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/confirm/$token'
      preLoaderRoute: typeof ConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/subscribers': {
      id: '/admin_/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/send': {
      id: '/admin_/send'
      path: '/admin/send'
      fullPath: '/admin/send'
      preLoaderRoute: typeof AdminSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/issues': {
      id: '/admin_/issues'
      path: '/admin/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/issues_/$id': {
      id: '/admin_/issues_/$id'
      path: '/admin/issues/$id'
      fullPath: '/admin/issues/$id'
      preLoaderRoute: typeof AdminIssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  AdminIssuesRoute: AdminIssuesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSendRoute: AdminSendRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  ConfirmTokenRoute: ConfirmTokenRoute,
  IssuesSlugRoute: IssuesSlugRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  AdminIssuesIdRoute: AdminIssuesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
